replicaCount: 1

image:
  repository: ghcr.io/galihru/snn-expression-detection
  tag: v1.1.0
  pullPolicy: IfNotPresent

cameraDevice: "/dev/video0"

securityContext:
  capabilities:
    add: ["SYS_RAWIO"]
  privileged: false

resources:
  limits:
    memory: "1Gi"
    cpu: "800m"
  requests:
    memory: "512Mi"
    cpu: "300m"

nodeSelector:
  accelerator: neuromorphic

tolerations:
  - key: "accelerator"
    operator: "Equal"
    value: "neuromorphic"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64
