apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "snn-expression-detection.serviceAccountName" . }}
  labels:
    {{- include "snn-expression-detection.labels" . | nindent 4 }}
automountServiceAccountToken: false
