name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Clean and Package Helm Chart
        run: |
          # Bersihkan semua file lama
          rm -rf packaged-charts
          mkdir -p packaged-charts

          # Buat package chart baru
          helm package helm-chart/ -d packaged-charts

          # Buat index.yaml baru (overwrite langsung)
          helm repo index packaged-charts --url https://raw.githubusercontent.com/${{ github.repository }}/main/packaged-charts/

          # Tambahkan artifacthub-repo.yml jika ada
          if [ -f artifacthub-repo.yml ]; then
            cp artifacthub-repo.yml packaged-charts/
          fi

          # Tampilkan isi
          ls -la packaged-charts
          cat packaged-charts/index.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add packaged-charts/
          git commit -m "Update Helm chart package and index [skip ci]" || echo "No changes to commit"
          git push origin main

      - name: Display Helm Repository URL
        run: |
          echo "🔗 Helm Repository URL:"
          echo "https://raw.githubusercontent.com/${{ github.repository }}/main/packaged-charts/"
          echo ""
          echo "📦 Package Index:"
          echo "https://raw.githubusercontent.com/${{ github.repository }}/main/packaged-charts/index.yaml"
